var user = require('../Database/Model/User');
var Post = require('../Database/Model/Posts');
var Brand = require('../Database/Model/Brand');
var Plans = require('../Database/Model/Plans');
var jwt = require("jsonwebtoken");
const axios = require('axios');
const { IgApiClient } = require('instagram-private-api');
const { get } = require('request-promise');
const CronJob = require("cron").CronJob
const schedule = require('node-schedule');
const Transporter = require('../Mail/Transporter');
var { LocalStorage } = require('node-localstorage');
const serverfile = require('../server.js');
var upload = serverfile.upload
const Linekedin = require("../Controllers/LinkedIn");
const Instagram = require("../Controllers/Instagram");
const Facebook = require("../Controllers/Facebook");
const { post_to_pinterest } = require("../Controllers/Pinterest");
const { postToFacebook, getFbId, getAccessToken } = require("../Controllers/Facebook");

// constructor function to create a storage directory inside our project for all our localStorage setItem.
var localStorage = new LocalStorage('./Localstorage');

exports.Post_To_All_SocialMedia_Immidiatly = async (req, res) => {
    try {

        var errorstaus = false;
        
        const errors = [];
          
        if (req.body.Platform && req.body.userid.match(/^[0-9a-fA-F]{24}$/) && req.body.Content && req.body.Brand && req.body.Brand.match(/^[0-9a-fA-F]{24}$/)) {

            const brandData = await Brand.findById(req.body.Brand);

            const post = new Post({
                userid: req.body.userid,
                Createdat: new Date(),
                Scheduledat: new Date(),
                Status: "Live",
                Platform: req.body.Platform,
                Content: req.body.Content,
                Image: req.body.mypic,
                Brand: req.body.Brand,
              });
            
            const post_saved = await post.save();
            
            if (req.body.Platform.includes("Pinterest")) {
                try {
                    const { title, board, content, url, mypic } = req.body;
                    post_to_pinterest(brandData,  title, content, board, url, mypic)
                } catch (error) {
                    res.json({
                        status: 0,
                        msg: error
                    })                   
                }
            }

            if (req.body.Platform.includes("facebook")) {
                try {
                    postToFacebook(
                        getFbId(brandData),
                        req.body.mypic,
                        req.body.Content,
                        getAccessToken(brandData),
                        post_saved.id
                      );
                } catch (error) {
                    console.log(error)
                    res.json({
                        status: 0,
                        msg: error
                    })                   
                }
            }

            var twitterPostID = "";                
            var twitterPostIDMSG = "";

            if (req.body.Platform.includes("Twitter")) {
                // const TwitterApi = require('twitter-api-v2');
                const { TwitterApi } = require('twitter-api-v2');
                console.log("-----------twit------------");
                const client = new TwitterApi({
                    appKey: "frE99Sn3FBj0pB43iTAuEiAny",
                    appSecret: "824gCARU9VA0MQAINXKcgkeSt8w8luXOF5O1KA20P3KaWUhwAs",
                    accessToken: branddata.twitterAccessToken,
                    accessSecret: branddata.twitterAccessSecret,
                  });
                if(req?.file?.filename){


                    try {
                            
                            // You can use media IDs generated by v1 API to send medias!
                            const mediaId = await client.v1.uploadMedia('./uploads/'+req?.file?.filename);
                            const response = await client.v2.tweetThread([
                            // 'Hello, lets talk about Twitter!',
                            { text: req.body.Content, media: { media_ids: [mediaId] } },
                            // 'This thread is automatically made with twitter-api-v2 :D',
                            ]);
                            twitterPostIDMSG = "Posted on Twitter succesfull";
                            twitterPostID = response[0].data.id;
                        } catch (error) {
                            twitterPostIDMSG = error.data.error;
                            // pinterestPostIDMSG = error.response.data.message;
                        }  
                    

                        // try {
                            
                        //     // You can use media IDs generated by v1 API to send medias!
                        //     const mediaId = await client.v1.uploadMedia('uploads/WhatsApp05.mp4','./uploads/'+req?.file?.filename);
                        //     const response = await client.v2.tweetThread([
                        //     // 'Hello, lets talk about Twitter!',
                        //     { text: req.body.Content, media: { media_ids: [mediaId] } },
                        //     // 'This thread is automatically made with twitter-api-v2 :D',
                        //     ]);
                        //     twitterPostIDMSG = "Posted on Twitter succesfull";
                        //     twitterPostID = response[0].data.id;
                        // } catch (error) {
                        //     twitterPostIDMSG = error.data.error;
                        //     // pinterestPostIDMSG = error.response.data.message;
                        // }  

                    
                }else{
                    const { data: createdTweet } = await client.v2.tweet(req.body.Content);
                    console.log('Tweet', createdTweet.id, ':', createdTweet.text);
                }
            }


            if (req.body.Platform.includes("Linkedin")) { 

                const { linkdinCredential } = brandData;

                const linkedIn_access_token = linkdinCredential.values().next().value;

                try {
                    console.log(`Organization`)
                    const organizationResponse = await axios.get(`https://api.linkedin.com/v2/companySearch?q=search&query=postager`,{
                        headers: {
                            'Authorization': `Bearer ${linkedIn_access_token}`
                        }
                    })
                    console.log(`Organization Data: ${organizationResponse.data}`)
                    // const profileResponse = await axios.get(`https://api.linkedin.com/v2/me`, {
                    //     headers: {
                    //         'Authorization': `Bearer ${linkedIn_access_token}`
                    //     }
                    // })
                    // console.log(`Profile ID: ${profileResponse.data?.id}`)
                    const postResponse = await axios("https://api.linkedin.com/rest/posts", {
                        method: "POST",
                        headers: {
                            'LinkedIn-Version': '202306',
                            'X-Restli-Protocol-Version': '2.0.0',
                            'Authorization': 'Bearer ' + linkedIn_access_token
                        },
                        data: JSON.stringify({
                            "author": `urn:li:person:${profileResponse.data?.id}`,
                            "commentary": req.body.Content,
                            "visibility": "PUBLIC",
                            "distribution": {
                                "feedDistribution": "MAIN_FEED",
                                "targetEntities": [],
                                "thirdPartyDistributionChannels": []
                            },
                            "lifecycleState": "PUBLISHED",
                        })
                    })
                } catch (error) {
                    res.status(500).send(error);
                }
            }            


            currentPoststack.push(post_saved._id);
            await user.updateOne({ "_id": req.body.userid }, { "Posts": currentPoststack }, function (error, response) {
                if (error) {
                    console.log(error);
                }
            });
            res.json({ msg: `Posted successfully to ${req.body.Platform.join(',')}`, status: 1 });
            
        }
        else {
            res.json({
                status: 0,
                msg: "Send All Necessary and valid Details"
            })
        }
    } catch (err) {
        res.json({
            status: 0,
            msg: "error in Server"
        })
        console.log(err);
    }
}
exports.Post_To_All_SocialMedia_Scheduling = async (req, res) => {
    console.log("Here")
    if (req.body.Platform && req.body.Date && req.body.userid.match(/^[0-9a-fA-F]{24}$/) && req.body.Content && req.body.Brand) {
        try {
            var userdata = await user.findById(req.body.userid)
            console.log("Platforms", req.body.Platform);

            var post = new Post({
                userid: req.body.userid,
                Createdat: new Date(),
                Scheduledat: new Date(),
                Status: "Live",
                Platform: req.body.Platform,
                Content: Content,
                Image: Image,
                Brand: req.body.Brand
            });
            var post_saved = await post.save();
            if(!userdata) {
                res.json({
                    status: 0,
                    msg: "check your Credentials or internal server error"
                })
            }
            if (req.body.Platform.includes("Facebook")) {

                localStorage.setItem("Facebook " + post_saved._id, "Post Scheduled at " + date + "current timing" + new Date());
                schedule.scheduleJob(req.body.Date, async function () {
                    posttoFacebookScheduled(userdata.facebookid, Image, Content, userdata.facebooktoken, post_saved._id)
                })
            }

            if (req.body.Platform.includes("Pinterest")) {


                const { ptcredential } = brandData;

                const pinterest_access_token = ptcredential.values().next().value;

                const { title, board, content, url } = req.body;

                localStorage.setItem("Pintrest" + post_saved._id, " Post Scheduled at " + date + "current timing" + new Date());
                
                schedule.scheduleJob(req.body.Date, async function () {
                    schedule_pinterest_post(pinterest_access_token, title, content, board, url)
                })
            }

        } catch(error) {
            res.json({
                status: 500,
                msg: error
            })
        }


        res.json({
            code: 1,
            msg: "Post has been Scheduled succesfully"
        });

    }
    else {
        res.json({
            status: 0,
            msg: "Send All Necessary and valid Details"
        })
    }
}

exports.Show_All_Post = async (req, res) => {
    if (req.body.userid && req.body.userid.match(/^[0-9a-fA-F]{24}$/)) {
        Post.find({
            userid: req.body.userid,
            Brand: req.body.brandId
        }, function (err, result) {
            if (!err) {
                res.json({
                    status: 1,
                    data: result
                });
            }
            else {
                res.send("internal server error");
            }
        })
    }
    else {
        res.json({
            status: 0,
            msg: "Please enter Valid Credentials"
        })
    }
}

exports.Show_Scheduled_Post = async (req, res) => {
    if (req.body.userid && req.body.userid.match(/^[0-9a-fA-F]{24}$/)) {
        Post.find({
            userid: req.body.userid,
            Status: "Scheduled"
        }, function (err, result) {
            if (!err) {
                res.json({
                    status: 1,
                    data: result
                });
            }
            else {
                res.send("internal server error");
            }
        })
    }
    else {
        res.json({
            status: 0,
            msg: "Please enter Valid Credentials"
        })
    }
}

exports.Show_Live_Post = async (req, res) => {
    if (req.body.userid && req.body.userid.match(/^[0-9a-fA-F]{24}$/)) {
        Post.find({
            userid: req.body.userid,
            Status: 'Live'
        }, function (err, result) {


            if (!err) {
                res.json({
                    status: 1,
                    data: result

                });


            }
            else {

                res.send("Internal Server Error");
            }
        })
    }
    else {

        res.json({


            status: 0,
            msg: "Please enter Valid Credentials"

        })
    }

}
async function finalizePost(igUserId, mediaContainerId,accesstoken) {
    console.log(accesstoken);
    let mediaContainerStatusEndpoint = `https://graph.facebook.com/${mediaContainerId}?fields=status_code,status&access_token=${accesstoken}`;
    try {
        let { data: mediaContainerStatus } = await axios.get(mediaContainerStatusEndpoint);
        let { status_code, status } = mediaContainerStatus;
        if (status_code === 'ERROR') {
                //Return here
            console.log('ERROR')
        }
        if (status_code !== 'FINISHED') {
            console.log('FINISHED')
            setTimeout(async () => {
                //Wait For 5seconds and recursively check for the status of the uploaded video
                await finalizePost(igUserId, mediaContainerId);
            }, 5000);
        } else {
            //The video has been published, finalize the post here
            try {
                let mediaPublishResponse = await axios.post(`https://graph.facebook.com/${igUserId}/media_publish?creation_id=${mediaContainerId}&access_token=${targetAccessToken}`);
                //More code omitted
            } catch (e) {

            }
        }
    } catch (e) {
        console.log(e.response.data)
    }
}
exports.Show_